language: python

python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install nose
  - pip install coveralls
  - pip install json5
  - pip install flake8

script:
  - nosetests
  - coverage run test.py
  - flake8
after_success:
  - coveralls
