language: python

python:
  - 3.3
  - 3.4
  - 3.5
os:
  - linux
before_install:
    - sudo apt-get update
install:
  - sudo apt-get install libportaudio-dev

  - pip install nose
  - pip install pyaudio
  - pip install coveralls
  - pip install json5
  - pip install flake8

script:
  - nosetests
  - coverage run test.py
  - flake8
after_success:
  - coveralls
